---
name: Apache2-AuthzNIS
version: 0.12
author:
  - 'Nguon Hao Ching <hao@iteaha.us>'
abstract: mod_perl2 NIS Group Authorization module
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::NIS: 0
build_requires:
  Test::More: 0
recommends:
  mod_perl2: 0
provides:
  Apache2::AuthzNIS:
    file: lib/Apache2/AuthzNIS.pm
    version: 0.12
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
